# Generated by Django 5.0.1 on 2024-05-21 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_id', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('U', 'USSD')], default='U', max_length=1)),
                ('status', models.CharField(choices=[('P', 'PENDING')], default='P', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AddMoneyTransactions',
        ),
    ]
