# Generated by Django 5.0.1 on 2024-05-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_addmoneytransaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoneytransaction',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('S', 'SUCCESSFUL'), ('F', 'FAILED')], default='P', max_length=1),
        ),
    ]
