# Generated by Django 5.0.1 on 2024-06-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_addmoneytransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmoneytransaction',
            name='tr_ref',
            field=models.CharField(default='no_trans_ref', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addmoneytransaction',
            name='method',
            field=models.CharField(choices=[('U', 'USSD'), ('T', 'Bank Transfer')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='addmoneytransaction',
            name='tr_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
