# Generated by Django 5.0.1 on 2024-06-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_addmoneytransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoneytransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='addmoneytransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
