# Generated by Django 5.0.1 on 2024-06-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_addmoneytransaction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoneytransaction',
            name='method',
            field=models.CharField(choices=[('USSD', 'USSD'), ('Bank Transfer', 'Bank Transfer')], default='USSD', max_length=15),
        ),
        migrations.AlterField(
            model_name='addmoneytransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('successful', 'successful'), ('failed', 'failed')], default='pending', max_length=10),
        ),
    ]
