# Generated by Django 5.0.1 on 2024-06-22 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyAirtimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=11)),
                ('price', models.PositiveIntegerField()),
                ('amount', models.CharField(max_length=5)),
                ('NP', models.CharField(choices=[('MTN', 'MTN'), ('GLO', 'GLO'), ('Airtel', 'Airtel'), ('9mobile', '9mobile')], max_length=7)),
                ('action', models.CharField(choices=[('R', 'Received'), ('S', 'Self'), ('G', 'Gift')], max_length=8)),
                ('service', models.CharField(choices=[('D', 'Data'), ('A', 'Airtime')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
