# Generated by Django 5.0.1 on 2024-06-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyairtimedata',
            old_name='NP',
            new_name='np',
        ),
    ]
