# Generated by Django 5.0.1 on 2024-06-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0005_buyairtimedata_tr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyairtimedata',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('successful', 'successful'), ('failed', 'failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='buyairtimedata',
            name='action',
            field=models.CharField(choices=[('Self', 'Self'), ('Gift', 'Gift')], max_length=8),
        ),
        migrations.AlterField(
            model_name='buyairtimedata',
            name='np',
            field=models.CharField(choices=[('MTN', 'MTN'), ('GLO', 'GLO'), ('AIRTEL', 'AIRTEL'), ('9MOBILE', '9MOBILE')], max_length=7),
        ),
    ]
