# Generated by Django 5.0.1 on 2024-06-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0006_buyairtimedata_status_alter_buyairtimedata_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyairtimedata',
            name='price',
            field=models.FloatField(),
        ),
    ]
