# Generated by Django 5.0.1 on 2024-06-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0007_alter_buyairtimedata_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyairtimedata',
            name='amount',
            field=models.CharField(max_length=7),
        ),
    ]
